### ISSUE TITLE
Allow us to choose the server to use?

### ISSUE THREAD

**Issue by raxele123** [Xeio/IdleCodeRedeemer#11]
Let us choose between ps19, ps20, ps21, ps22, and ps23? (Pretty sure ps23 is retired right now though.) Sometimes different servers run better than others. Perhaps you can also add something to detect which server is running better when refreshing inventory?

**Comment by Xeio** [comment]
Probably won't really do this. I mostly mirror how the game actually works behind the scenes, it makes a request to the master server which gives a server to use, and only swaps servers if it gets a swap-server command back.

If you want to hard-code a specific server in you could modify [this line](https://github.com/Xeio/IdleCodeRedeemer/blob/1963074d76b872a057b1c804087914cf228831fe/extension/dst/chestManagement.js#LL387C6-L387C6) and give it a server like https://ps22.idlechampions.com/~idledragons/post.php at the start, though it will still swap if the server asks it to. Then you could just load that extension folder directly into your browser (rather than from the Chrome store)
